name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x, 1.18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - run: go get -t -v ./...
      - run: GOOS=linux go build
      - run: GOOS=darwin go build
      - run: GOOS=freebsd go build
      - run: GOOS=windows go build
      - run: GOARCH=386 go build
