name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - run: go test -v -cover -shuffle=on ./...
      - run: go test -v -cover -shuffle=on -race ./...
